version: "3.8" # specify docker-compose version

# Define the services/containers to be run
services:
  cook17_ng: 
    build: 
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: cook17_ng
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    ports:
      - "4217:4200" 
      - "49153:49153"
    environment:
      - NODE_ENV=dev

  cook17_ts:
    build:
      context: ./api_ts
      dockerfile: Dockerfile.dev
    container_name: cook17_ts
    volumes:
      - ./api_ts:/api_ts
      - /api_ts/node_modules
    ports:
      - "6017:3000"


  cook17_database:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: example

  cook17_adminer:
    image: adminer
    #restart: always
    ports:
      - 9017:8080

  cook17_mongo:
    image: mongo
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cook17_mongo_admin:
    image: mongo-express
    #restart: always
    ports:
      - 10017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  cook17_nginx: 
    build: loadbalancer 
    container_name: cook17_nginx
    ports:
      - "8017:80" 
    links:
      - cook17_ts
      - cook17_ng

