version: "3.8" # specify docker-compose version

# Define the services/containers to be run
services:
# cook17_angular: 
#   build: 
#     context: ./ui_angular
#     dockerfile: Dockerfile.dev
#   container_name: cook17_angular
#   volumes:
#     - ./ui_angular:/ui_angular
#     - /ui_angular/node_modules
#   ports:
#     - "4217:4200" 
#     - "49153:49153"
#   environment:
#     - NODE_ENV=dev

  cook17_ts:
    build:
      context: ./api_ts
      dockerfile: Dockerfile.dev
    container_name: cook17_ts
    volumes:
      - ./api_ts:/api_ts
      - /api_ts/node_modules
    ports:
      - "6017:3000"


  cook17_database:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: example

  cook17_adminer:
    image: adminer
    #restart: always
    ports:
      - 9017:8080

  cook17_nginx: 
    build: loadbalancer 
    container_name: cook17_nginx
    ports:
      - "8017:80" 
    links:
      - cook17_ts
#      - cook17_angular

