version: "3.8" # specify docker-compose version

# Define the services/containers to be run
services:
  cook17_ng: 
    build: 
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: cook17_ng
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    ports:
      - "4217:4200" 
      - "49153:49153"
    environment:
      - NODE_ENV=dev
    networks:
      - default 
    depends_on:
      - cook17_ts
      - cook17_js

  cook17_js:
    build:
      context: ./api_js
      dockerfile: Dockerfile.dev
    container_name: cook17_js
    volumes:
      - ./api_js:/api_js
      - /api_js/node_modules
    ports:
      - "5017:5000"
    networks:
      - default 
    depends_on:
      - cook17_database
      - cook17_mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cook17_mongo:27017/"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  cook17_ts:
    build:
      context: ./api_ts
      dockerfile: Dockerfile.dev
    container_name: cook17_ts
    volumes:
      - ./api_ts:/api_ts
      - /api_ts/node_modules
    ports:
      - "6017:3000"
    networks:
      - default 
    depends_on:
      - cook17_database
      - cook17_mongo

  cook17_adminer:
    image: adminer
    restart: always
    ports:
      - 9017:8080
    networks:
      - default 
    depends_on:
      - cook17_database
      - cook17_mongo

  cook17_database:
    image: postgres
    #restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - default

  cook17_mongo:
    image: mongo
    #restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default 

  cook17_mongo_admin:
    image: mongo-express
    restart: always
    ports:
      - 10017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - default 
    depends_on:
      - cook17_mongo

  cook17_nginx: 
    build: loadbalancer 
    container_name: cook17_nginx
#    restart: always
    ports:
      - "8017:80" 
    networks:
      - default 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cook17_ng:4217/"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - cook17_ts
      - cook17_ng
      - cook17_js

networks:
  default:
